### ISSUE TITLE
I can not download anime segmentation dataset.

### ISSUE THREAD

**Issue by UdonDa** [jerryli27/AniSeg#2]
In README.md, you write the download link, which is https://github.com/jerryli27/AniSeg/blob/master.
However, I think this is wrong path.
Would I ask the correct the dataset link?

**Comment by ak9250** [comment]
same question here would like to get link to the segmentation dataset

**Comment by jerryli27** [comment]
I can share the dataset. It will take me a bit to put it in the right format. I'll get back to you in a week or two, if that's okay.

**Comment by jerryli27** [comment]
I open sourced the dataset. You can find it here: https://drive.google.com/open?id=1fnFbRQKuAUlfgVZnLEapg-rI_Zz5_H5D

Please reopen the issue if you want the tfrecords for training as well.
