### ISSUE TITLE
README: link 'Danbooru2019 Figures', 855k crops using AniSeg

### ISSUE THREAD

**Issue by gwern** [jerryli27/AniSeg#8]
I've run AniSeg on Danbooru2019 solo SFW images to generate a large corpus of close-up single-character whole-body/profile images to help our BigGAN learn bodies. The dataset, and my code for how to generate it, is likely of interest to AniSeg users. Writeup: https://www.gwern.net/Crops#danbooru2019-figures

**Comment by jerryli27** [comment]
Hey Gwern, great work on generating the dataset and on BigGAN, as always.
I'll spend some time this week to incorporate the changes you suggested
earlier and link your work to the readme. Thanks!!
